deployment:
  tasks:
    - export DEPLOYDIR="$HOME/sistemaescolar.princeton.edu.mx/"
    - /bin/rsync -a --exclude=".git" --exclude="node_modules" --exclude="vendor" ./ $DEPLOYDIR

    - cd $DEPLOYDIR

    # Instalar dependencias PHP (con PHP 8.3)
    - /usr/local/bin/ea-php83 /usr/local/bin/composer install --no-dev --optimize-autoloader

    # Instalar dependencias JS
    - npm install
    - npm run build

    # Permisos
    - chmod -R 775 storage
    - chmod -R 775 bootstrap/cache

    # Cache y optimización con PHP 8.3
    - /usr/local/bin/ea-php83 artisan config:cache
    - /usr/local/bin/ea-php83 artisan route:cache
    - /usr/local/bin/ea-php83 artisan view:cache
    - /usr/local/bin/ea-php83 artisan optimize